### ISSUE TITLE
No cameras available

### ISSUE THREAD

**Issue by tiagofreire-pt** [nyxnyx/xmeye#1]
Hi.

I'm trying this custom component on HA 0.105.3 with this config:

```yaml
camera:
  - platform: xmeye
    name: 'DG-XME'
    host: '192.168.10.200'
    port: '34567'
    username: 'admin_username_redacted'
    password: 'admin_password_redacted'
```

No errors detected in the HA log and no camera is available on 'unused entities' page.
